### ISSUE TITLE
How do you get the value of the slider OR rangeSlider?

### ISSUE THREAD

**Issue by phiasco12** [Aleinbanger/al-range-slider#1]
How do you get the value of the slider OR rangeSlider?

this key information is missing from this plugin!

its all pretty but doesn't have a great documents to explain this information!

**Comment by phiasco12** [comment]
something like `onchange` when the slider is initialised?!?

**Comment by Aleinbanger** [comment]
@phiasco12 Yes, you can use `onChange` callback, passing it to the config like this:
```ts
$('.js-example-class').alRangeSlider({
  onChange: (state) => {
    console.log(state?.selectedValues);
  },
});
```
Or you can read the values from the inputs, which should be created automatically with the default config.

Please note that the plugin isn't really production ready. It's a practical task (assignment) and hasn't gone through code review yet.
