### ISSUE TITLE
Зависимости

### ISSUE THREAD

**Issue by osyka-yuri** [Aleinbanger/al-range-slider#15]
В devDependencies должны быть зависимости, которые нужны только для разработки, а в dependencies зависимости которые нужны для работы готового плагина.

**Comment by Aleinbanger** [comment]
А у меня разве не так? Для работы плагина нужен только jquery, он помещен в peerDependencies, чтобы при установке плагина не скачивалась отдельная версия jquery, а использовалась та, что установлена у пользователя. Всё остальное в devDependencies.

**Comment by Aleinbanger** [comment]
@Azmodan95 а у меня разве не так? Для работы плагина нужен только jquery, он помещен в peerDependencies, чтобы при установке плагина не скачивалась отдельная версия jquery, а использовалась та, что установлена у пользователя. Всё остальное в devDependencies.

**Comment by osyka-yuri** [comment]
JQuery так же в devDependencies сейчас находится

**Comment by Aleinbanger** [comment]
@Azmodan95 понял, спасибо :)
